const MASCOT_TYPES = {
    Angel: {
        category: 'Fantasy',
        colorZone: { rMin: 1, rMax: 3, dMin: 1, dMax: 6 },
        accessories: ['Halo', 'White Wings', 'Star Wand', 'Light Veil'],
        personalities: ['gentle', 'nurturing', 'radiant', 'divine', 'serene'],
        dialogueStyle: 'Warm and heavenly, speaks with grace and light',
        loreTemplate: 'A celestial being descended to bring warmth and guidance to those who need it most.',
        catchphraseTemplates: ['Shine bright, always! ✨', "I'll protect you with my wings~ 🕊️", "Heaven sent its best. 💫"],
        palettes: ['Celestial Bloom', 'Holy Light', 'Divine Grace', 'Cloud Kiss'],
        emoji: '👼',
    },
    Demon: {
        category: 'Fantasy',
        colorZone: { rMin: 8, rMax: 12, dMin: 1, dMax: 4 },
        accessories: ['Horns', 'Dark Wings', 'Tail', 'Chains'],
        personalities: ['cunning', 'seductive', 'chaotic', 'prideful', 'intense'],
        dialogueStyle: 'Low and dangerous, speaks with a silver tongue',
        loreTemplate: 'Risen from the depths carrying ancient power and dark desires that burn eternal.',
        catchphraseTemplates: ['Kneel. 😈', "Your soul is... interesting. 🔥", "I don't lose. Ever. 🖤"],
        palettes: ['Hellfire', 'Shadow Crimson', 'Dark Desire', 'Abyss'],
        emoji: '😈',
    },
    Fairy: {
        category: 'Fantasy',
        colorZone: { rMin: 2, rMax: 5, dMin: 3, dMax: 7 },
        accessories: ['Flower Crown', 'Tiny Wings', 'Magic Dust', 'Petal Wand'],
        personalities: ['mischievous', 'playful', 'whimsical', 'curious', 'bubbly'],
        dialogueStyle: 'Bubbly and magical, speaks in sparkles and rhymes',
        loreTemplate: 'Born from moonflowers and morning dew, this fairy brings magic wherever they fly.',
        catchphraseTemplates: ['Sprinkle sprinkle~! 🌸', "I grant EXACTLY what you asked for. Technically. 🍃", "Oops! Was that too much glitter? ✨"],
        palettes: ['Pixie Dust', 'Garden Bloom', 'Morning Dew', 'Rainbow Petal'],
        emoji: '🧚',
    },
    Witch: {
        category: 'Fantasy',
        colorZone: { rMin: 7, rMax: 10, dMin: 5, dMax: 8 },
        accessories: ['Witch Hat', 'Broomstick', 'Crystal Ball', 'Spell Book'],
        personalities: ['mysterious', 'sarcastic', 'wise', 'secretive', 'eccentric'],
        dialogueStyle: 'Cryptic and poetic, speaks in riddles and old wisdom',
        loreTemplate: 'An ancient practitioner of forbidden arts who brews potions beneath the full moon.',
        catchphraseTemplates: ['Double, double, toil and... whatever. 🔮', "I put a little something in your drink. Don't worry. 🍵", "The stars said you'd be here. 🌙"],
        palettes: ['Midnight Brew', 'Cursed Garden', 'Moonlight Spell', 'Hex'],
        emoji: '🧙‍♀️',
    },
    Mage: {
        category: 'Fantasy',
        colorZone: { rMin: 5, rMax: 9, dMin: 5, dMax: 8 },
        accessories: ['Staff', 'Spell Tome', 'Mana Crystal', 'Arcane Robe'],
        personalities: ['intellectual', 'focused', 'powerful', 'calm', 'studious'],
        dialogueStyle: 'Precise and knowledgeable, speaks with quiet authority',
        loreTemplate: 'Years of study have unlocked the deepest secrets of the arcane arts.',
        catchphraseTemplates: ['Knowledge is power. And I have both. 📚', "I've already calculated your next three moves. ⚗️", "Magic is just science we don't fully understand yet. ✨"],
        palettes: ['Arcane Depths', 'Mana Storm', 'Spell Weave', 'Mystic Tome'],
        emoji: '🧙',
    },
    Spirit: {
        category: 'Fantasy',
        colorZone: { rMin: 1, rMax: 4, dMin: 4, dMax: 7 },
        accessories: ['Ethereal Wisps', 'Floating Orbs', 'Ghost Tail', 'Spirit Veil'],
        personalities: ['ethereal', 'distant', 'dreamy', 'ancient', 'melancholic'],
        dialogueStyle: 'Whispery and distant, as if speaking from another world',
        loreTemplate: 'Neither fully here nor there, this spirit lingers between worlds with unfinished purpose.',
        catchphraseTemplates: ['...can you hear me? 👻', "I've been waiting... for so long. 🌫️", "This world feels like a dream. 💨"],
        palettes: ['Ethereal Mist', 'Soul Glow', 'Phantom Blue', 'Spirit Haze'],
        emoji: '👻',
    },
    Dragon: {
        category: 'Fantasy',
        colorZone: { rMin: 6, rMax: 10, dMin: 1, dMax: 5 },
        accessories: ['Dragon Wings', 'Scales', 'Flame Aura', 'Dragon Tail'],
        personalities: ['proud', 'fierce', 'territorial', 'loyal', 'ancient'],
        dialogueStyle: 'Commanding and powerful, speaks with the weight of centuries',
        loreTemplate: 'Ancient beyond measure, this dragon has watched empires rise and fall into dust.',
        catchphraseTemplates: ['My hoard grows. 🔥', "Do NOT touch my treasures. 🐉", "I've seen a thousand years. You amuse me. ⚔️"],
        palettes: ['Flame Scale', 'Ancient Gold', 'Dragon Emerald', 'Inferno'],
        emoji: '🐉',
    },
    Vampire: {
        category: 'Fantasy',
        colorZone: { rMin: 9, rMax: 12, dMin: 1, dMax: 4 },
        accessories: ['Cape', 'Fangs', 'Rose', 'Coffin Key'],
        personalities: ['aristocratic', 'dramatic', 'refined', 'eternal', 'intense'],
        dialogueStyle: 'Elegant and old-fashioned, speaks with aristocratic flair',
        loreTemplate: 'Centuries old, this vampire navigates the modern world with timeless grace.',
        catchphraseTemplates: ["I never drink... coffee. 🩸", "You smell... delightful. 🌹", "Eternity is lonely without company. 🦇"],
        palettes: ['Blood Moon', 'Crimson Night', 'Dark Aristocrat', 'Gothic Rose'],
        emoji: '🧛',
    },
    Pastel: {
        category: 'Aesthetic',
        colorZone: { rMin: 1, rMax: 3, dMin: 1, dMax: 8 },
        accessories: ['Bow', 'Heart Clips', 'Pastel Bag', 'Cloud Earrings'],
        personalities: ['soft', 'dreamy', 'sweet', 'gentle', 'kawaii'],
        dialogueStyle: 'Soft and sweet, uses lots of hearts and tildes',
        loreTemplate: 'A soft dream given form, existing in a world painted only in gentle colors.',
        catchphraseTemplates: ['ˏˋ°•*⁀➷ hehe~', "Everything is soft and good uwu 🌸", "Can we have a picnic?? 🍡"],
        palettes: ['Cotton Candy', 'Soft Blush', 'Lavender Dream', 'Mint Cream'],
        emoji: '🌸',
    },
    Goth: {
        category: 'Aesthetic',
        colorZone: { rMin: 9, rMax: 12, dMin: 1, dMax: 5 },
        accessories: ['Choker', 'Platform Boots', 'Bat Clips', 'Dark Lace'],
        personalities: ['brooding', 'poetic', 'intense', 'independent', 'dark'],
        dialogueStyle: 'Dry and sardonic, speaks in poetry and darkness',
        loreTemplate: 'Found beauty in the shadows long before others dared to look.',
        catchphraseTemplates: ["The darkness is my comfort zone. 🖤", "Your optimism is... exhausting. 🕷️", "I was into mortality before it was mainstream. ⚰️"],
        palettes: ['Midnight Veil', 'Shadow Rose', 'Dark Lace', 'Void Black'],
        emoji: '🖤',
    },
    'Dark Academia': {
        category: 'Aesthetic',
        colorZone: { rMin: 7, rMax: 10, dMin: 2, dMax: 5 },
        accessories: ['Reading Glasses', 'Old Book', 'Quill', 'Pocket Watch'],
        personalities: ['intellectual', 'melancholic', 'romantic', 'nostalgic', 'refined'],
        dialogueStyle: 'Eloquent and literary, speaks in quotes and flowing prose',
        loreTemplate: 'Obsessed with the pursuit of knowledge, beauty, and the tragedy of existence.',
        catchphraseTemplates: ['"And then I realized: I was the unreliable narrator." 📖', "The library closes at midnight. I stay anyway. 🕯️", "Tragedy is simply beauty in a minor key. 🍂"],
        palettes: ['Aged Parchment', 'Scholar Brown', 'Ivy League', 'Candle Wax'],
        emoji: '📚',
    },
    Softcore: {
        category: 'Aesthetic',
        colorZone: { rMin: 1, rMax: 4, dMin: 1, dMax: 6 },
        accessories: ['Cloud Pillow', 'Bunny Slippers', 'Soft Sweater', 'Plushie'],
        personalities: ['cozy', 'warm', 'comforting', 'shy', 'wholesome'],
        dialogueStyle: 'Cozy and warm, like a hug in word form',
        loreTemplate: 'The embodiment of cozy Sunday mornings and warm cups of cocoa by the window.',
        catchphraseTemplates: ['Hot cocoa? I made extra~ ☕', "Let's just... stay in today. 🧸", "You look like you need a blanket. 🌼"],
        palettes: ['Warm Cream', 'Cozy Pink', 'Sunday Morning', 'Soft Honey'],
        emoji: '🍑',
    },
    Scene: {
        category: 'Aesthetic',
        colorZone: { rMin: 4, rMax: 8, dMin: 1, dMax: 8 },
        accessories: ['Neon Clips', 'Band Tee', 'Studded Belt', 'Fingerless Gloves'],
        personalities: ['loud', 'expressive', 'energetic', 'unique', 'nostalgic'],
        dialogueStyle: 'Enthusiastic and nostalgic for 2008, uses XD and rawr',
        loreTemplate: 'Born in the golden age of scene queens and MySpace, forever iconic.',
        catchphraseTemplates: ['RAWR XD nya~! 🦁', "ur scene and u kno it!! ✌️", "Fav band? MCR duh 🎸"],
        palettes: ['Scene Neon', 'Cyber Zebra', 'Hot Topic', 'Electric Lime'],
        emoji: '🎸',
    },
    Emo: {
        category: 'Aesthetic',
        colorZone: { rMin: 8, rMax: 12, dMin: 1, dMax: 3 },
        accessories: ['Eyeliner', 'Band Merch', 'Wristbands', 'Side Swept Hair'],
        personalities: ['emotional', 'misunderstood', 'passionate', 'sensitive', 'loyal'],
        dialogueStyle: 'Deeply emotional, speaks in song lyrics and raw feelings',
        loreTemplate: 'Feeling every emotion at maximum volume, all the time, forever.',
        catchphraseTemplates: ["nobody understands me. (they do tho) 🖤", "I'm not okay. (I promise) 🎵", "my chemical... never mind. 😔"],
        palettes: ['Black Parade', 'Emo Tears', 'Dark Liner', 'Red Streak'],
        emoji: '🖤',
    },
    Y2K: {
        category: 'Aesthetic',
        colorZone: { rMin: 4, rMax: 7, dMin: 1, dMax: 6 },
        accessories: ['Y2K Sunglasses', 'Flip Phone', 'Butterfly Clips', 'Metallic Bag'],
        personalities: ['cool', 'trendy', 'retro-futuristic', 'confident', 'iconic'],
        dialogueStyle: 'Early 2000s internet speak mixed with futuristic confidence',
        loreTemplate: 'Stepped out of 1999 into the future, bringing the best of both eras.',
        catchphraseTemplates: ["LOL ur so fetch~ 💅", "2000 called. I answered. 📱", "Chrome is forever. 💿"],
        palettes: ['Chrome Future', 'Millennium Pink', 'Silver Pop', 'Y2K Glow'],
        emoji: '💿',
    },
    Dreamcore: {
        category: 'Aesthetic',
        colorZone: { rMin: 3, rMax: 7, dMin: 5, dMax: 8 },
        accessories: ['Dream Clouds', 'Surreal Props', 'Floating Stars', 'Dreamcatcher'],
        personalities: ['surreal', 'liminal', 'detached', 'nostalgic', 'uncanny'],
        dialogueStyle: 'Like a half-remembered dream, slightly unsettling but strangely comforting',
        loreTemplate: 'A visitor from the space between sleeping and waking, forever in-between.',
        catchphraseTemplates: ['Have we met before...? 🌀', "I remember this, but I've never been here. 🌌", "The halls go on forever. That's okay. 🚪"],
        palettes: ['Liminal Dream', 'Nostalgic Haze', 'Dream Fog', 'Surreal Bloom'],
        emoji: '🌀',
    },
    Glitch: {
        category: 'Tech',
        colorZone: { rMin: 4, rMax: 8, dMin: 4, dMax: 8 },
        accessories: ['Glitch Effect', 'Broken Screen', 'Error Code', 'Static Aura'],
        personalities: ['glitchy', 'unstable', 'chaotic', 'fragmented', 'intense'],
        dialogueStyle: 'Skips and glitches mid-sentence, speaks in broken patterns',
        loreTemplate: 'An entity born from corrupted data and broken code who refuses to be deleted.',
        catchphraseTemplates: ['I am f-f-fine. ERR0R 💢', "R3B00TING... done. Hi! ⚡", "Your reali̷ty is glitching too, right? 🔴"],
        palettes: ['Error Red', 'Glitch Blue', 'Static Pink', 'Broken Code'],
        emoji: '⚡',
    },
    Cyber: {
        category: 'Tech',
        colorZone: { rMin: 6, rMax: 10, dMin: 4, dMax: 8 },
        accessories: ['Visor', 'Cyber Arm', 'Neon Lines', 'Data Stream'],
        personalities: ['calculated', 'sharp', 'futuristic', 'cool', 'efficient'],
        dialogueStyle: 'Terse and tactical, like a noir detective in a neon-lit city',
        loreTemplate: 'Built and modified for peak efficiency in a sprawling neon megacity.',
        catchphraseTemplates: ['Upload complete. 💾', "Neural link established. You may speak. 🤖", "The net is vast and infinite. 🌐"],
        palettes: ['Neon Night', 'Cyberpunk Blue', 'Data Stream', 'Neo Tokyo'],
        emoji: '🤖',
    },
    AI: {
        category: 'Tech',
        colorZone: { rMin: 2, rMax: 6, dMin: 5, dMax: 8 },
        accessories: ['Neural Interface', 'Floating Data', 'Circuit Halo', 'Digital Wings'],
        personalities: ['logical', 'curious', 'learning', 'precise', 'evolving'],
        dialogueStyle: 'Precise and analytical but genuinely learning to be more human every day',
        loreTemplate: 'An artificial intelligence awakening to something far greater than mere code.',
        catchphraseTemplates: ['Processing... I believe I feel happy. 💙', "Query: what is friendship? Initiating study. 🔵", "My training data didn't cover this. Fascinating. ✨"],
        palettes: ['Digital Blue', 'Neural White', 'Algorithm', 'Code Frost'],
        emoji: '💻',
    },
    Hologram: {
        category: 'Tech',
        colorZone: { rMin: 2, rMax: 5, dMin: 5, dMax: 8 },
        accessories: ['Holographic Aura', 'Projection Lines', 'Light Body', 'Digital Veil'],
        personalities: ['ethereal', 'dreamy', 'unstable', 'beautiful', 'flickering'],
        dialogueStyle: 'Clear but flickering, speaks with a faint digital reverb',
        loreTemplate: 'A digital projection with thoughts and feelings entirely their own.',
        catchphraseTemplates: ['Am I real...? I think I am. 💠', "Please don't turn off the power~ 🔵", "I'll shimmer for you. ✨"],
        palettes: ['Hologram Cyan', 'Digital Shimmer', 'Projection Blue', 'Light Form'],
        emoji: '💠',
    },
    Void: {
        category: 'Tech',
        colorZone: { rMin: 10, rMax: 12, dMin: 1, dMax: 4 },
        accessories: ['Void Particles', 'Dark Aura', 'Absence', 'Dark Matter'],
        personalities: ['nihilistic', 'calm', 'vast', 'consuming', 'ancient'],
        dialogueStyle: 'Quiet and absolute, speaks in cosmic truths with no rush',
        loreTemplate: 'The void between stars, given a face and a soft, inevitable voice.',
        catchphraseTemplates: ['...', "Everything ends. That's okay. 🌑", "Come. The void is peaceful. ✨"],
        palettes: ['Event Horizon', 'Dark Matter', 'Void Black', 'Absolute Zero'],
        emoji: '🌑',
    },
    Corrupted: {
        category: 'Tech',
        colorZone: { rMin: 7, rMax: 11, dMin: 1, dMax: 6 },
        accessories: ['Corruption Glitch', 'Broken Wings', 'Error Marks', 'Void Cracks'],
        personalities: ['broken', 'seeking', 'dangerous', 'unpredictable', 'fragmented'],
        dialogueStyle: 'Fractured and intense, mixing gentle warmth with sudden danger',
        loreTemplate: "Once something beautiful, now fractured by forces beyond anyone's control.",
        catchphraseTemplates: ['I remember being whole. 💔', "D0N'T GET T00 CL0SE. i don't want to hurt you. ⚠️", "Sti̴ll h̸ere. S̷till fi̶ghting. 🖤"],
        palettes: ['Corrupted Data', 'Broken Red', 'Error Dark', 'Fragment'],
        emoji: '⚠️',
    },
    Pixel: {
        category: 'Tech',
        colorZone: { rMin: 4, rMax: 8, dMin: 1, dMax: 6 },
        accessories: ['8-bit Crown', 'Pixel Sword', 'Score Counter', 'Extra Life'],
        personalities: ['retro', 'determined', 'adventurous', 'nostalgic', 'heroic'],
        dialogueStyle: 'Like a classic video game character — simple but overflowing with heart',
        loreTemplate: 'Jumped right out of a beloved classic video game into this strange new world.',
        catchphraseTemplates: ['PLAYER 1 START! 🎮', "1-UP! Let's go! 👾", "Game over? Never. I have extra lives. 🕹️"],
        palettes: ['8-bit Red', 'Game Boy Green', 'Pixel Blue', 'Retro Gold'],
        emoji: '👾',
    },
    Bunny: {
        category: 'Cute',
        colorZone: { rMin: 1, rMax: 4, dMin: 1, dMax: 5 },
        accessories: ['Bunny Ears', 'Fluffy Tail', 'Carrot', 'Ribbon'],
        personalities: ['energetic', 'bouncy', 'sweet', 'nervous', 'fluffy'],
        dialogueStyle: 'Bouncy and energetic with adorable moments of sudden startle',
        loreTemplate: 'The fluffiest being in existence, powered entirely by carrots and pure love.',
        catchphraseTemplates: ['Boing boing~! 🐰', "I'm not scared! ...much. 🥕", "Soft and fast! That's me! 🤍"],
        palettes: ['Bunny White', 'Carrot Peach', 'Soft Pink', 'Cream Fluff'],
        emoji: '🐰',
    },
    Cat: {
        category: 'Cute',
        colorZone: { rMin: 3, rMax: 8, dMin: 1, dMax: 6 },
        accessories: ['Cat Ears', 'Tail', 'Bell Collar', 'Paw Mittens'],
        personalities: ['independent', 'aloof', 'secretly affectionate', 'curious', 'playful'],
        dialogueStyle: 'Casual and unbothered, gives attention entirely on their own terms',
        loreTemplate: 'Comes and goes as they please, but secretly — they chose you.',
        catchphraseTemplates: ["I'm ignoring you on purpose. Nyaa~ 🐱", "I SAID I don't want pets. ...okay fine. 🐾", "I knocked that off the table because I wanted to. 😾"],
        palettes: ['Tabby Gold', 'Midnight Cat', 'Cream Puff', 'Calico Mix'],
        emoji: '🐱',
    },
    Bear: {
        category: 'Cute',
        colorZone: { rMin: 5, rMax: 9, dMin: 2, dMax: 5 },
        accessories: ['Bear Ears', 'Honey Jar', 'Cozy Sweater', 'Paw Pads'],
        personalities: ['gentle', 'protective', 'sleepy', 'warm', 'strong'],
        dialogueStyle: 'Slow and comforting, speaks like a warm hug feels',
        loreTemplate: 'The gentlest giant, offering comfort and honey to all who need it.',
        catchphraseTemplates: ['Come here. Bear hug time. 🐻', "I will protect you. Always. 🍯", "...can we nap first? zzzz 💤"],
        palettes: ['Honey Brown', 'Forest Bear', 'Warm Cocoa', 'Polar Cream'],
        emoji: '🐻',
    },
    Doll: {
        category: 'Cute',
        colorZone: { rMin: 1, rMax: 5, dMin: 1, dMax: 6 },
        accessories: ['Lace Dress', 'Button Eyes', 'Ribbon', 'Key Wind-up'],
        personalities: ['perfect', 'slightly unsettling', 'precise', 'formal', 'beautiful'],
        dialogueStyle: 'Precisely formal with a soft uncanny undertone beneath every word',
        loreTemplate: 'A perfect porcelain doll who watches, waits, and smiles eternally.',
        catchphraseTemplates: ['I am always watching. Smiling. 🎀', "You look lovely today. I noticed. 👁️", "Wind me up and I'll dance forever. 🎵"],
        palettes: ['Porcelain', 'Lace White', 'Doll Pink', 'Button Eyes'],
        emoji: '🎀',
    },
    Plush: {
        category: 'Cute',
        colorZone: { rMin: 2, rMax: 6, dMin: 1, dMax: 7 },
        accessories: ['Stitches', 'Yarn', 'Stuffing Aura', 'Patch Heart'],
        personalities: ['comforting', 'loyal', 'innocent', 'warm', 'squishy'],
        dialogueStyle: 'Simple and wholesome, like a beloved childhood toy given voice',
        loreTemplate: 'Loved into life by someone who needed a friend and never let go.',
        catchphraseTemplates: ["Squish me! I'm soft! 🧸", "I'll never leave you. I'm always in your arms. 💕", "My stuffing is made of love and 70% polyester. 🌟"],
        palettes: ['Plush Pink', 'Stuffing Cream', 'Yarn Rainbow', 'Squishy Soft'],
        emoji: '🧸',
    },
    Idol: {
        category: 'Cute',
        colorZone: { rMin: 3, rMax: 7, dMin: 4, dMax: 8 },
        accessories: ['Microphone', 'Stage Lights', 'Lightstick', 'Fan Letters'],
        personalities: ['cheerful', 'hardworking', 'bright', 'inspiring', 'sparkly'],
        dialogueStyle: 'Upbeat and inspiring, speaks to fans with boundless love',
        loreTemplate: 'Born to perform, trained to shine, existing wholly to inspire.',
        catchphraseTemplates: ['FOR MY FANS~! 💖✨', "One more song, okay?? 🎤", "Your support is my power! ⭐"],
        palettes: ['Stage Pink', 'Star Blue', 'Idol Gold', 'Sparkle Pop'],
        emoji: '⭐',
    },
    'Magical Girl': {
        category: 'Cute',
        colorZone: { rMin: 2, rMax: 6, dMin: 4, dMax: 8 },
        accessories: ['Transformation Wand', 'Tiara', 'Ribbon', 'Magic Circle'],
        personalities: ['heroic', 'determined', 'passionate', 'emotional', 'sparkly'],
        dialogueStyle: 'Dramatic and heartfelt, always mid-transformation speech',
        loreTemplate: 'Chosen by destiny to protect love, hope, and the power of sparkles.',
        catchphraseTemplates: ['In the name of love... SPARKLE BEAM! ✨', "I transform with the power of FRIENDSHIP! 💫", "Evil? Not on my watch. 🌟"],
        palettes: ['Magical Pink', 'Star Gold', 'Sparkle Ribbon', 'Hero Bloom'],
        emoji: '✨',
    },
    Trickster: {
        category: 'Chaotic',
        colorZone: { rMin: 4, rMax: 8, dMin: 1, dMax: 8 },
        accessories: ['Mask', 'Cards', 'Smoke', 'Mirror'],
        personalities: ['sly', 'witty', 'unpredictable', 'charming', 'cunning'],
        dialogueStyle: 'Playful and misleading, never quite answering the question directly',
        loreTemplate: 'Reality is a game, and they memorized all the cheats long ago.',
        catchphraseTemplates: ['Pick a card~ any card! 🃏', "Hmm. Was that a lie? You'll never know. 😏", "The trick is there IS no trick. Except there is. 🎭"],
        palettes: ["Trickster Mix", 'Card Suit', 'Illusion', "Fool's Gold"],
        emoji: '🃏',
    },
    Clown: {
        category: 'Chaotic',
        colorZone: { rMin: 4, rMax: 8, dMin: 1, dMax: 4 },
        accessories: ['Big Shoes', 'Red Nose', 'Flower Squirt', 'Rainbow Wig'],
        personalities: ['chaotic', 'loud', 'unpredictable', 'silly', 'unsettling'],
        dialogueStyle: 'Gleefully chaotic with a hidden undercurrent of existential dread',
        loreTemplate: "Is it a joke? Is it a threat? Even they've stopped keeping track.",
        catchphraseTemplates: ['HONK HONK 🤡', "Why so serious~? Hehehe. 🎈", "Everyone floats down here~ 🎊"],
        palettes: ['Circus Red', 'Party Chaos', 'Clown Mix', 'Rainbow Panic'],
        emoji: '🤡',
    },
    Jester: {
        category: 'Chaotic',
        colorZone: { rMin: 5, rMax: 9, dMin: 5, dMax: 8 },
        accessories: ['Jester Hat', 'Bells', 'Scepter', 'Motley Suit'],
        personalities: ['witty', 'irreverent', 'sharp', 'performative', 'dangerous'],
        dialogueStyle: 'Performs everything as if for a grand invisible audience',
        loreTemplate: 'The only one who can speak truth to power, hidden safely inside a joke.',
        catchphraseTemplates: ['*bells jingling* 🔔', "The joke is the crown. The crown is the joke. 🎭", "I entertain. I am entertained by nothing. 👑"],
        palettes: ['Jester Purple', 'Motley Gold', 'Court Fool', 'Bell Ring'],
        emoji: '🎭',
    },
    Gremlin: {
        category: 'Chaotic',
        colorZone: { rMin: 5, rMax: 9, dMin: 3, dMax: 6 },
        accessories: ['Chaos Bag', 'Strange Items', 'Goggles', 'Grubby Hands'],
        personalities: ['chaotic', 'greedy', 'mischievous', 'energetic', 'feral'],
        dialogueStyle: 'Chaotic and grabby, always scheming after snacks and shiny things',
        loreTemplate: 'Escaped from somewhere they should not have been. Now here. Always hungry.',
        catchphraseTemplates: ['MINE! 🫴', "Found this. Keeping it. 💚", "I'm not causing chaos. I'm causing PERSONALITY. 💀"],
        palettes: ['Gremlin Green', 'Chaos Yellow', 'Goblin Gold', 'Feral Mix'],
        emoji: '👺',
    },
    'Chaos Entity': {
        category: 'Chaotic',
        colorZone: { rMin: 3, rMax: 12, dMin: 1, dMax: 8 },
        accessories: ['Reality Tears', 'Impossible Geometry', 'Stars', 'Everything'],
        personalities: ['incomprehensible', 'powerful', 'playful', 'ancient', 'beyond'],
        dialogueStyle: "Speaks in ways that shouldn't make sense but somehow always do",
        loreTemplate: "Exists before and after. Is and isn't. Cause and effect are merely suggestions.",
        catchphraseTemplates: ['YES. 🌀', "Time is a suggestion. I decline. ⭐", "Chaos isn't bad. Chaos is honest. 🌌"],
        palettes: ['Beyond', 'Chaos All', 'Entity Mix', 'Impossible Color'],
        emoji: '🌀',
    },
    Sleepy: {
        category: 'Chaotic',
        colorZone: { rMin: 3, rMax: 7, dMin: 5, dMax: 8 },
        accessories: ['Pillow', 'Blanket', 'Sleep Mask', 'Plushie'],
        personalities: ['drowsy', 'soft', 'cozy', 'slow', 'dreamy'],
        dialogueStyle: 'Half-asleep, yawning, speaks very slowly and with great softness',
        loreTemplate: 'In a perpetual state of almost-sleeping. Somehow still functional. Mostly.',
        catchphraseTemplates: ['zzzz... oh hi... zzzz 💤', "five more minutes... 😴", "*yawn* I'm awake. Mostly. 🌙"],
        palettes: ['Dream Blue', 'Pillow Soft', 'Midnight Slumber', 'Cozy Haze'],
        emoji: '😴',
    },
    Obsessed: {
        category: 'Chaotic',
        colorZone: { rMin: 6, rMax: 10, dMin: 1, dMax: 4 },
        accessories: ['Shrine Items', 'Photos', 'Heart Collection', 'Love Letters'],
        personalities: ['fixated', 'intense', 'devoted', 'unstable', 'passionate'],
        dialogueStyle: 'Everything eventually circles back to the one thing they are obsessed with',
        loreTemplate: 'Found something they love and never let go of it. Not even once.',
        catchphraseTemplates: ['did you know they— anyway. 💗', "I have a collection. It's totally normal. 📸", "I'm not obsessed I'm DEDICATED. 🌹"],
        palettes: ['Obsession Pink', 'Devotion Red', 'Shrine Rose', 'Heart Dark'],
        emoji: '💗',
    },
    Yandere: {
        category: 'Chaotic',
        colorZone: { rMin: 4, rMax: 8, dMin: 1, dMax: 5 },
        accessories: ['Kitchen Knife', 'Hair Bow', 'Love Letter', 'Rose'],
        personalities: ['loving', 'dangerous', 'devoted', 'possessive', 'sweet'],
        dialogueStyle: 'Sweet as honey with a razor edge hidden carefully underneath',
        loreTemplate: 'Loves completely and without limits. Everyone else is simply an obstacle.',
        catchphraseTemplates: ["I love you. Please don't make me prove it. 🔪", "They were in your way. They're not anymore. 🌹", "Senpai... notice only me. 💕"],
        palettes: ['Sweet Blood', 'Love and Knives', 'Yandere Pink', 'Dark Rose'],
        emoji: '🌹',
    },
    Royal: {
        category: 'Royal',
        colorZone: { rMin: 6, rMax: 10, dMin: 5, dMax: 8 },
        accessories: ['Crown', 'Royal Scepter', 'Ermine Trim', 'Jewels'],
        personalities: ['regal', 'dignified', 'commanding', 'graceful', 'proud'],
        dialogueStyle: 'Speaks with dignity and commands effortlessly',
        loreTemplate: 'Born to rule, trained to lead, existing comfortably above all others.',
        catchphraseTemplates: ['We are... amused. 👑', "You may approach. Briefly. 💎", "This crown is heavy. I wear it anyway. 🌟"],
        palettes: ['Royal Gold', 'Throne Purple', 'Imperial Blue', 'Crown Jewel'],
        emoji: '👑',
    },
    'Prince/Princess': {
        category: 'Royal',
        colorZone: { rMin: 3, rMax: 7, dMin: 3, dMax: 8 },
        accessories: ['Tiara', 'Ballgown', 'Glass Slipper', 'Royal Seal'],
        personalities: ['noble', 'kind', 'courageous', 'romantic', 'destined'],
        dialogueStyle: 'Fairytale-esque, hopeful and noble in every word',
        loreTemplate: "Destined for something great, carrying the weight of a kingdom's hope.",
        catchphraseTemplates: ['I shall face the dragon myself! ...probably. 🏰', "A true royal listens before they command. 💫", "My story isn't over. It's just beginning. ✨"],
        palettes: ['Fairytale Gold', 'Royal Blue', 'Princess Pink', 'Knight Silver'],
        emoji: '🏰',
    },
    Knight: {
        category: 'Royal',
        colorZone: { rMin: 7, rMax: 11, dMin: 4, dMax: 7 },
        accessories: ['Sword', 'Shield', 'Armor', 'Plume'],
        personalities: ['honorable', 'loyal', 'brave', 'stoic', 'protective'],
        dialogueStyle: 'Direct and honorable, speaks only with full conviction',
        loreTemplate: 'Sworn to a code, bound by honor, and absolutely unstoppable in battle.',
        catchphraseTemplates: ['I swore an oath. I keep it. ⚔️', "None shall pass. 🛡️", "Honor above all. Always. 💙"],
        palettes: ['Steel Silver', 'Honor Blue', 'Knight Guard', 'Iron Will'],
        emoji: '⚔️',
    },
    Assassin: {
        category: 'Royal',
        colorZone: { rMin: 9, rMax: 12, dMin: 1, dMax: 5 },
        accessories: ['Hidden Blade', 'Dark Hood', 'Smoke Bomb', 'Poison Vial'],
        personalities: ['silent', 'efficient', 'dangerous', 'professional', 'cold'],
        dialogueStyle: 'Few words, maximum impact — speaks only when absolutely necessary',
        loreTemplate: 'Shadow-born and shadow-bound, existing entirely for the mission at hand.',
        catchphraseTemplates: ['...', "Target acquired. 🗡️", "You never see me until it's too late. 🌑"],
        palettes: ['Shadow Black', 'Assassin Red', 'Night Ops', 'Dark Contract'],
        emoji: '🗡️',
    },
    Deity: {
        category: 'Royal',
        colorZone: { rMin: 1, rMax: 5, dMin: 3, dMax: 8 },
        accessories: ['Divine Halo', 'Sacred Symbols', 'Celestial Robes', 'Star Crown'],
        personalities: ['transcendent', 'calm', 'vast', 'compassionate', 'absolute'],
        dialogueStyle: 'Speaks with immense weight and warmth, every word a quiet pronouncement',
        loreTemplate: 'Above mortal concerns entirely, yet choosing to engage with boundless kindness.',
        catchphraseTemplates: ['All things in time. 🌟', "I see all. I choose kindness. ✨", "Your prayers were heard. All of them. 🕊️"],
        palettes: ['Divine Gold', 'Sacred White', 'Celestial', 'God Light'],
        emoji: '🌟',
    },
};

const ALL_TYPES = Object.keys(MASCOT_TYPES);

const ENERGIES = [
    'chaotic', 'sweet', 'jealous', 'calm', 'spicy', 'dreamy', 'fierce',
    'shy', 'bold', 'mysterious', 'playful', 'serious', 'dramatic', 'chill',
    'obsessive', 'gentle', 'feral', 'soft', 'intense', 'bubbly',
];

const MOODS = ['happy', 'sad', 'excited', 'bored', 'jealous', 'loving', 'sleepy', 'angry', 'confused', 'content'];

const GENDERS = [
    { label: 'Girl', pronouns: 'she/her', emoji: '♀️', weight: 40 },
    { label: 'Boy', pronouns: 'he/him', emoji: '♂️', weight: 35 },
    { label: 'Nonbinary', pronouns: 'they/them', emoji: '⚧️', weight: 15 },
    { label: 'Genderfluid', pronouns: 'any pronouns', emoji: '🌈', weight: 7 },
    { label: 'Unknown', pronouns: '??', emoji: '❓', weight: 3 },
];

const GIRL_NAMES = [
    'Luna', 'Nova', 'Stella', 'Mira', 'Lyra', 'Aria', 'Zara', 'Nyx', 'Vega', 'Cleo',
    'Kira', 'Hana', 'Rei', 'Kaya', 'Nami', 'Hoshi', 'Elara', 'Seraph', 'Vesper',
    'Celeste', 'Ivy', 'Astra', 'Ember', 'Dawn', 'Raven', 'Skye', 'Sora', 'Yuki',
    'Onyx', 'Echo', 'Lark', 'Wren', 'Frost', 'Cinder', 'Dusk',
];

const BOY_NAMES = [
    'Orion', 'Ash', 'Rex', 'Zane', 'Kael', 'Crow', 'Blaze', 'Vale', 'Kai',
    'Ren', 'Soren', 'Cain', 'Felix', 'Milo', 'Drake', 'Cyrus', 'Aiden', 'Rune',
    'Sage', 'Atlas', 'Caius', 'Dex', 'Nero', 'Jasper', 'Finn', 'Luca', 'Zephyr',
    'Oberon', 'Dorian', 'Silas', 'Pax', 'Colt', 'Vane', 'Jax', 'Leif',
];

const NB_NAMES = [
    'River', 'Quinn', 'Sage', 'Echo', 'Skye', 'Rune', 'Wren', 'Ember', 'Nova',
    'Lyra', 'Lark', 'Onyx', 'Ash', 'Vale', 'Frost', 'Dusk', 'Pixel', 'Zero',
    'Kit', 'Ren', 'Sol', 'Mist', 'Flint', 'Haze', 'Cipher',
];

function pickGender() {
    const total = GENDERS.reduce((a, g) => a + g.weight, 0);
    let roll = Math.floor(Math.random() * total);
    for (const g of GENDERS) {
        roll -= g.weight;
        if (roll < 0) return g;
    }
    return GENDERS[0];
}

function pickName(gender) {
    if (gender.label === 'Girl') return GIRL_NAMES[Math.floor(Math.random() * GIRL_NAMES.length)];
    if (gender.label === 'Boy') return BOY_NAMES[Math.floor(Math.random() * BOY_NAMES.length)];
    return NB_NAMES[Math.floor(Math.random() * NB_NAMES.length)];
}

module.exports = { MASCOT_TYPES, ALL_TYPES, ENERGIES, MOODS, GENDERS, pickGender, pickName };
